[package]
name = "signed_integer"
version = "0.1.0"
authors = ["MSNTCS <najafi@codechain.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
cw20 = { version = "0.13.1" }
cosmwasm-storage = { version = "1.0.0-beta7" }
cosmwasm-std = { version = "1.0.0-beta7" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }